// <auto-generated />
namespace IRecordweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class USP_Company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(USP_Company));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120634075_USP_Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
