var header_url = "https://mangeshirecord.github.io/HTML/"; 
document.write('');

document.write('<ul class="metismenu list-unstyled" id="side-menu">');
    document.write('<li class="topmenu_1">');
        document.write('<a href="'+header_url+'dashboard.html">');
            document.write('<i class="la la-home"></i>');
            document.write('<span>Dashboard</span>');
        document.write('</a>');
    document.write('</li>');
    document.write('<li class="topmenu_2">');
        document.write('<a href="javascript: void(0);" class="has-arrow waves-effect">');
            document.write('<i class="la la-sitemap"></i>');
            document.write('<span>Masters</span>');
        document.write('</a>');
        document.write('<ul class="sub-menu" aria-expanded="false">');
            document.write('<li class="submenu_1"><a href="'+header_url+'scripts-master.html">Script Master</a></li>');
            document.write('<li class="submenu_2"><a href="'+header_url+'family-master.html">Family Master</a></li>');
            document.write('<li class="submenu_3"><a href="'+header_url+'member-master.html">Member Master</a></li>');
            document.write('<li class="submenu_4"><a href="'+header_url+'group-master.html">Group Master</a></li>');
            document.write('<li class="submenu_5"><a href="'+header_url+'other-invesment-master.html">Other Invesment Master</a></li>');
            document.write('<li class="submenu_6"><a href="'+header_url+'industry-master.html">Industry Master</a></li>');
            document.write('<li class="submenu_7"><a href="'+header_url+'narration-master.html">Narration Master</a></li>');
            document.write('<li class="submenu_8"><a href="'+header_url+'consultant-master.html">Consultant Master</a></li>');
            document.write('<li class="submenu_9"><a href="'+header_url+'account-master.html">Account Master</a></li>');
            document.write('<li class="submenu_10"><a href="'+header_url+'entry-trade/list.html">Broker Bill</a></li>');
            document.write('<li class="submenu_11"><a href="'+header_url+'bank-statement/list.html">Bank Statement</a></li>');
        document.write('</ul>');
    document.write('</li>');
    document.write('<li class="topmenu_3">');
        document.write('<a href="'+header_url+'bonus-entry-screen.html">');
            document.write('<i class="las la-gift"></i>');
            document.write('<span>Bonus Entry</span>');
        document.write('</a>');
    document.write('</li>');
    document.write('<li class="topmenu_4">');
        document.write('<a href="'+header_url+'user-security.html">');
            document.write('<i class="las la-user-cog"></i>');
            document.write('<span>User Security</span>');
        document.write('</a>');
    document.write('</li>');
    document.write('<li class="topmenu_5">');
        document.write('<a href="javascript: void(0);" class="has-arrow waves-effect">');
            document.write('<i class="la la-clipboard-list"></i>');
            document.write('<span>Reports</span>');
        document.write('</a>');
        document.write('<ul class="sub-menu" aria-expanded="false">');
            document.write('<li class="reports_1"><a href="'+header_url+'reports/jv-reports.html">JV Reports</a></li>');
        document.write('</ul>');
    document.write('</li>');
document.write('</ul>');